# ======
# STYLUA
# ======

# Indentation width in spaces
indent_width = 2

# Use tabs instead of spaces
indent_type = "Tabs"

# Quote style for strings ("Auto", "Single", "Double")
quote_style = "Auto"

# Column width before wrapping
column_width = 120

# How to handle line endings: "Unix", "Windows", "Auto"
line_endings = "Unix"

# Whether to add a trailing comma in tables
call_parentheses = "Always"
